/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entidade.Usuario;
import Utils.Sessao;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        getRootPane().setDefaultButton(btnEntrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfdUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        pfdSenha = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(tfdUsuario);
        tfdUsuario.setBounds(210, 140, 120, 20);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 102));
        lblUsuario.setText("Usuário:");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(140, 140, 60, 17);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 102));
        lblSenha.setText("Senha:");
        jPanel1.add(lblSenha);
        lblSenha.setBounds(140, 170, 60, 17);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(210, 200, 120, 23);

        pfdSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfdSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(pfdSenha);
        pfdSenha.setBounds(210, 170, 120, 20);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/logo_easyroom_small-removebg-preview.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(160, 10, 190, 130);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/quarto3.jpg"))); // NOI18N
        lblFundo.setOpaque(true);
        jPanel1.add(lblFundo);
        lblFundo.setBounds(-210, -190, 770, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(512, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pfdSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfdSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfdSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String user = tfdUsuario.getText();
        String password = pfdSenha.getText();
        if (user.equals("admin") && password.equals("admin")) { //VERIFICAÇÃO AQUI SERÁ PROVENIENTE DO BANCO
            //LOGOU
            //SETA O USUÁRIO NA SESSÃO
            Sessao.getInstance().setUsuario(new Usuario(user, password));
            Sessao.getInstance().setPermissao(0);
            //ABRE A TELA INICIAL AGORA
            new FrmPrincipal().setVisible(true);//VEJA QUE NÃO PASSEI O OBJETO DE SESSÃO
            this.dispose();
        }
        
        else{
            //LOGOU
            //SETA O USUÁRIO NA SESSÃO
            Sessao.getInstance().setUsuario(new Usuario(user, password));
            Sessao.getInstance().setPermissao(1);
            //ABRE A TELA INICIAL AGORA
            new FrmPrincipal().setVisible(true);//VEJA QUE NÃO PASSEI O OBJETO DE SESSÃO
            this.dispose();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfdSenha;
    private javax.swing.JTextField tfdUsuario;
    // End of variables declaration//GEN-END:variables
}
