/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import TableModel.AuditoriaTableModel;
import Utils.JTableUtilities;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;

/**
 *
 * @author evand
 */
public class IfrAuditoria extends javax.swing.JInternalFrame {
    
    AuditoriaTableModel tableModel = new AuditoriaTableModel();
    
    public IfrAuditoria() {
        initComponents();
        startDefaultComponents();
        getRootPane().setDefaultButton(btnBuscar);
        tblAudit.setModel(tableModel);
        this.setTitle("Auditoria do Sistema");
        JTableUtilities.setCellsAlignment(tblAudit, SwingConstants.CENTER, new int[]{0, 1, 2, 3});
        tblAudit.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        // JTableUtilities.setWidthAsPercentages(tblAudit, 0.25f, 0.25f, 0.25f, 0.25f);
    }
    
    private void startDefaultComponents() {
        rbUsuario.setSelected(true);
        //rbInsert.setSelected(true);
        pnlOps.setVisible(false);

        //Alterar futuramente com novas melhorias
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcoes = new javax.swing.ButtonGroup();
        bgOps = new javax.swing.ButtonGroup();
        pnlMostraInfos = new javax.swing.JPanel();
        scrTableAudit = new javax.swing.JScrollPane();
        tblAudit = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        pnlBusca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCriterio = new javax.swing.JLabel();
        tfdCriterio = new javax.swing.JTextField();
        pnlOpcoes = new javax.swing.JPanel();
        btnRelAudit = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        rbUsuario = new javax.swing.JRadioButton();
        rbTabela = new javax.swing.JRadioButton();
        rbOperacao = new javax.swing.JRadioButton();
        pnlOps = new javax.swing.JPanel();
        rbInsert = new javax.swing.JRadioButton();
        rbUpdate = new javax.swing.JRadioButton();
        rbDelete = new javax.swing.JRadioButton();

        tblAudit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrTableAudit.setViewportView(tblAudit);

        javax.swing.GroupLayout pnlMostraInfosLayout = new javax.swing.GroupLayout(pnlMostraInfos);
        pnlMostraInfos.setLayout(pnlMostraInfosLayout);
        pnlMostraInfosLayout.setHorizontalGroup(
            pnlMostraInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrTableAudit, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        pnlMostraInfosLayout.setVerticalGroup(
            pnlMostraInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMostraInfosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrTableAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        pnlBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel1.setText("Buscar por:");

        lblCriterio.setText("Critério:");

        pnlOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        btnRelAudit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/reports.png"))); // NOI18N
        btnRelAudit.setText("Gerar Relatório");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/search-30.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcoesLayout = new javax.swing.GroupLayout(pnlOpcoes);
        pnlOpcoes.setLayout(pnlOpcoesLayout);
        pnlOpcoesLayout.setHorizontalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelAudit, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOpcoesLayout.setVerticalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRelAudit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bgOpcoes.add(rbUsuario);
        rbUsuario.setText("Usuário");

        bgOpcoes.add(rbTabela);
        rbTabela.setText("Tabela");

        bgOpcoes.add(rbOperacao);
        rbOperacao.setText("Operação");
        rbOperacao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbOperacaoStateChanged(evt);
            }
        });

        pnlOps.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolha uma opção de operação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N

        bgOps.add(rbInsert);
        rbInsert.setText("Insert");

        bgOps.add(rbUpdate);
        rbUpdate.setText("Update");

        bgOps.add(rbDelete);
        rbDelete.setText("Delete");

        javax.swing.GroupLayout pnlOpsLayout = new javax.swing.GroupLayout(pnlOps);
        pnlOps.setLayout(pnlOpsLayout);
        pnlOpsLayout.setHorizontalGroup(
            pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbInsert)
                .addGap(50, 50, 50)
                .addComponent(rbUpdate)
                .addGap(30, 30, 30)
                .addComponent(rbDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOpsLayout.setVerticalGroup(
            pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbUpdate)
                    .addComponent(rbInsert)
                    .addComponent(rbDelete)))
        );

        javax.swing.GroupLayout pnlBuscaLayout = new javax.swing.GroupLayout(pnlBusca);
        pnlBusca.setLayout(pnlBuscaLayout);
        pnlBuscaLayout.setHorizontalGroup(
            pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscaLayout.createSequentialGroup()
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlBuscaLayout.createSequentialGroup()
                        .addComponent(lblCriterio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdCriterio))
                    .addGroup(pnlBuscaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rbUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbOperacao))
                    .addComponent(pnlOps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBuscaLayout.setVerticalGroup(
            pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscaLayout.createSequentialGroup()
                        .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rbUsuario)
                            .addComponent(rbTabela)
                            .addComponent(rbOperacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlOps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCriterio)
                            .addComponent(tfdCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscaLayout.createSequentialGroup()
                        .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlMostraInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(pnlMostraInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void rbOperacaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbOperacaoStateChanged
        if (!rbOperacao.isSelected()) {
            pnlOps.setVisible(false);
        } else {
            pnlOps.setVisible(true);
        }
    }//GEN-LAST:event_rbOperacaoStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //GERENCIAR AS BUSCAS
        //CHECAR O QUE ESTÁ MARCADO
        String operacao = "";
        String usuario = "";
        String tabela = "";
        if (rbOperacao.isSelected()) {
            if (rbInsert.isSelected()) {
                operacao = "INSERT";
            } else if (rbUpdate.isSelected()) {
                operacao = "UPDATE";
            } else if (rbDelete.isSelected()) {
                operacao = "DELETE";
            }
        }
        if (rbUsuario.isSelected()) {
            usuario = tfdCriterio.getText();
        } else if (rbTabela.isSelected()) {
            tabela = tfdCriterio.getText();
        }
        this.tableModel.updateData(usuario, operacao, tabela);
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcoes;
    private javax.swing.ButtonGroup bgOps;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRelAudit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCriterio;
    private javax.swing.JPanel pnlBusca;
    private javax.swing.JPanel pnlMostraInfos;
    private javax.swing.JPanel pnlOpcoes;
    private javax.swing.JPanel pnlOps;
    private javax.swing.JRadioButton rbDelete;
    private javax.swing.JRadioButton rbInsert;
    private javax.swing.JRadioButton rbOperacao;
    private javax.swing.JRadioButton rbTabela;
    private javax.swing.JRadioButton rbUpdate;
    private javax.swing.JRadioButton rbUsuario;
    private javax.swing.JScrollPane scrTableAudit;
    private javax.swing.JTable tblAudit;
    private javax.swing.JTextField tfdCriterio;
    // End of variables declaration//GEN-END:variables
}
